apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  autoInjection:
    enabled: true
    components:
      injector:
        enabled: true
  defaultNamespace: istio-system
  gateways:
    enabled: true
    components:
      ingressGateway:
        enabled: true
      egressGateway:
        enabled: true
  values:
    gateways:
      istio-ingressgateway:
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    tracing:
      enabled: true
    pilot:
      traceSampling: "5.0"
    prometheus:
      enabled: true
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
      rewriteAppHTTPProbe: true
    kiali:
      enabled: true
      createDemoSecret: true
    global:
      mtls:
        auto: true
        enabled: false
      proxy:
        accessLogFile: "/dev/stdout"
      outboundTrafficPolicy:
        mode: REGISTRY_ONLY
      disablePolicyChecks: false
